### ISSUE TITLE
Code Organization and Naming Enhancement

### ISSUE THREAD

**Issue by Manered** [timmehz/MCPlugins#1]
Hey @timmehz,

I noticed that you're using names for your classes and variables that don't follow the usual rules in Java. I wanted to explain why it's important to follow these rules and how it can make your code easier to read.

**1. Class Names:**

- Class names should start with a capital letter.
- Instead of using names like `Ping_tablist`, it's better to use names like `PingTablist`.

**2. Variable Names:**

- Variable names should start with a lowercase letter.
- Instead of using names like `Ping_tablist`, it's better to use names like `pingTablist`.

**Following these naming conventions will make it easier for others (including yourself) to understand your code.**

It's also a good idea to include a file called `.gitignore` in your project. This file tells Git (the tool used for version control) to ignore certain files or folders when you save changes. This can help keep your repository clean by excluding files that don't need to be tracked.

You can find ready-made `.gitignore` templates for different programming languages on GitHub. These templates provide a starting point for excluding common files. You can choose the appropriate template for your project.

I hope this explanation helps! If you have any questions or need further assistance, please let me know.

**Comment by Manered** [comment]
Try giving this issue the label "enchancement". It'll help with organizing your issue page.

Another thing I'd like to say is that it's better to separate all of your Minecraft Plugins into multiple GitHub Repositories.

**Comment by timmehz** [comment]
I will do this just for you and others, I don't really care about readability/maintainability on my end because the plugin is quite small and since I wrote the plugin I know where everything is located, and what is what. Also I am not using Git, I am just uploading the files manually on Github.

**Comment by Manered** [comment]
Understood. By the way here's what I do when making my repositories.
I'm assuming that you're using IntelliJ.
1. Create the repository on GitHub, add a readme, license and configure the repository.
2. If you don't have GitHub desktop download it
3. Click the green button somewhere on the right side of the code view
4. Press the button that says "Open in GitHub Desktop
5. Set your default IDE (somewhere in the GitHub desktop settings
6. Open the repository in IDEA
7. There will be 2 notifications about Git. Press "Always add" on both of them.
8. Write code, do anything you'd like.
9. Return to the GitHub desktop window, where you will see your new changes. Commit them from there.

**Comment by timmehz** [comment]
Going to close this issue since both has been done/going to be done very soon.
